### PR TITLE
Fixes for Rails 3.1 and `in` Hash

### PR DESCRIPTION
**Pull request by budu**
Here's a couple of fixes I had to do to make Symbolize work in my apps.

### CODE REVIEW

**Comment by nofxx** [comment]
Do you have a failing example I can add to the tests? They were green =/

**Comment by budu** [comment]
I'll add some spec examples later and a fix, the last commit in this pull request is wrong.

**Comment by nofxx** [comment]
Hey budu, I did some of the specs and the fix. Update with master.
I just won't make the "value -> key" change. keys need to be keys ;)

**Comment by budu** [comment]
Yeah, I realized that yesterday but didn't had the time to send another fix.

**Pull request merged**
